"""Aggregate the pilot sweeps into FINDINGS.md.

Reads every results/*.json and writes a per-device summary plus the
cross-device comparisons that motivate the project: how much a bad
configuration costs, whether bad configurations announce themselves, and
whether a configuration tuned on one device stays good on another.
"""

import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "FINDINGS.md")

# Ordered oldest to newest so generation trends read left to right.
ORDER = ["Tesla T4", "NVIDIA L4", "NVIDIA A100", "NVIDIA H100", "NVIDIA RTX PRO 6000",
         "TPU v5 lite", "TPU v6 lite"]


def sort_key(name):
    for i, prefix in enumerate(ORDER):
        if name.startswith(prefix):
            return (i, name)
    return (len(ORDER), name)


def load():
    """One record per (device, dtype) sweep."""
    out = []
    for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "*.json"))):
        with open(path, encoding="utf-8") as f:
            blob = json.load(f)
        if "sweeps" not in blob and "results" not in blob:
            continue  # capability probes etc. — not sweep data
        sweeps = blob.get("sweeps") or [{
            "dtype": blob.get("dtype", "bf16"),
            "xla_ms": blob.get("xla_ms"),
            "results": blob["results"],
        }]
        for sweep in sweeps:
            rows = sweep.get("results", [])
            out.append({
                "device": blob["device"],
                "backend": "Mosaic (TPU)" if "TPU" in blob["device"] else "Triton (GPU)",
                "dtype": sweep.get("dtype", "bf16"),
                "xla_ms": sweep.get("xla_ms"),
                "rows": rows,
                "ok": [r for r in rows if r["status"] == "ok"],
                "failed": [r for r in rows if r["status"] != "ok"],
            })
    return sorted(out, key=lambda r: (sort_key(r["device"]), r["dtype"]))


def fmt(v, spec=".3f", dash="—"):
    return dash if v is None else format(v, spec)


def main():
    sweeps = load()
    lines = ["# Pilot findings", "",
             "Generated by `analysis/summarize.py` from `results/*.json`.",
             "A single 4096x4096x4096 matmul, swept over a small hand-picked",
             "configuration space on every accelerator Colab offers.", "",
             "## Per-device summary", "",
             "| Device | Backend | dtype | XLA | best Pallas | best vs XLA | spread | compiled but slow | failed to compile |",
             "|---|---|---|---:|---:|---:|---:|---:|---:|"]

    for s in sweeps:
        if not s["ok"]:
            lines.append(f"| {s['device']} | {s['backend']} | {s['dtype']} | "
                         f"{fmt(s['xla_ms'])} ms | none compiled | — | — | — | "
                         f"{len(s['failed'])}/{len(s['rows'])} |")
            continue
        best = min(s["ok"], key=lambda r: r["median_ms"])
        worst = max(s["ok"], key=lambda r: r["median_ms"])
        spread = worst["median_ms"] / best["median_ms"]
        # A config that compiles yet lands below half the best is a silent cliff.
        cliffs = [r for r in s["ok"] if r["median_ms"] > 2 * best["median_ms"]]
        cfg = "x".join(str(c) for c in best["config"])
        extra = ""
        if "num_warps" in best:
            extra = f" w{best['num_warps']}s{best['num_stages']}"
        lines.append(
            f"| {s['device']} | {s['backend']} | {s['dtype']} | {fmt(s['xla_ms'])} ms | "
            f"`{cfg}`{extra} {fmt(best['median_ms'])} ms | {best['vs_xla']:.2f}x | "
            f"{spread:.1f}x | {len(cliffs)}/{len(s['ok'])} | {len(s['failed'])}/{len(s['rows'])} |")

    lines += ["", "## How bad configurations announce themselves", "",
              "The two backends fail in different ways, which changes what an",
              "autotuner can prune for free.", ""]
    for s in sweeps:
        if not s["ok"] and s["failed"]:
            err = s["failed"][0].get("error", "")
            lines.append(f"- **{s['device']} ({s['dtype']})**: no configuration compiled. "
                         f"`{err[:120]}`")
        elif s["ok"]:
            best = min(s["ok"], key=lambda r: r["median_ms"])
            cliffs = [r for r in s["ok"] if r["median_ms"] > 2 * best["median_ms"]]
            if cliffs:
                w = max(cliffs, key=lambda r: r["median_ms"])
                cfg = "x".join(str(c) for c in w["config"])
                lines.append(
                    f"- **{s['device']} ({s['dtype']})**: `{cfg}` compiles cleanly and "
                    f"then runs {w['median_ms'] / best['median_ms']:.0f}x slower than the best "
                    f"config ({w['median_ms']:.1f} ms vs {best['median_ms']:.3f} ms) — "
                    f"no error, no warning.")
            if s["failed"]:
                err = s["failed"][0].get("error", "")
                cfg = "x".join(str(c) for c in s["failed"][0]["config"])
                lines.append(f"- **{s['device']} ({s['dtype']})**: `{cfg}` refuses to compile "
                             f"— `{err[:100]}`")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    # Windows consoles may be cp949/cp1252; don't let a preview kill the run.
    preview = "\n".join(lines[:40])
    print(preview.encode(sys.stdout.encoding or "utf-8", errors="replace")
          .decode(sys.stdout.encoding or "utf-8"))


if __name__ == "__main__":
    main()
